export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userContants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}

export const bookConstants = {
    GET_ALL_BOOKS: 'GET_ALL_BOOKS',
    GET_DETAIL_BOOK: 'GET_DETAIL_BOOK',
    PUT_EDIT_BOOK: 'PUT_EDIT_BOOK',
    POST_ADD_BOOK: 'POST_ADD_BOOK'
};
export const categoryConstants = {
    GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES'
}
export const publisherConstants = {
    GET_ALL_PUBLISHERS: 'GET_ALL_PUBLISHERS'
}

